spring:
  profiles:
    active: local

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

management:
  endpoints:
    web:
      base-path: /application
  endpoint:
    health:
      show-details: always